name: ci
on: push

env:
  NODE_VERSION: 18.16.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install pnpm
        run: npm install -g pnpm

      - run: pnpm install
      - run: pnpm test
